<?xml version="1.0" encoding="utf-8"?><Database Name="Monolito4am" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=NEO\CRISTOPHER;Initial Catalog=Monolito4am;Integrated Security=True;Encrypt=False" SettingsObjectName="Capa_Datos.Properties.Settings" SettingsPropertyName="Monolito4amConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_proveedor" Member="tbl_proveedor">
    <Type Name="tbl_proveedor">
      <Column Name="prov_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="prov_nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="prov_telefono" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="prov_direccion" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="prov_estado" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Association Name="tbl_proveedor_tbl_producto" Member="tbl_producto" ThisKey="prov_id" OtherKey="prov_id" Type="tbl_producto" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_producto" Member="tbl_producto">
    <Type Name="tbl_producto">
      <Column Name="pro_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="pro_nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="pro_cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pro_precio" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="prov_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pro_estado" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Association Name="tbl_proveedor_tbl_producto" Member="tbl_proveedor" ThisKey="prov_id" OtherKey="prov_id" Type="tbl_proveedor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_tipo_usuario" Member="tbl_tipo_usuario">
    <Type Name="tbl_tipo_usuario">
      <Column Name="tusu_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tusu_nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tusu_estado" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Association Name="tbl_tipo_usuario_tbl_usuario" Member="tbl_usuario" ThisKey="tusu_id" OtherKey="tusu_id" Type="tbl_usuario" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_usuario" Member="tbl_usuario">
    <Type Name="tbl_usuario">
      <Column Name="usu_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="usu_cedula" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="usu_nombres" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="usu_apellidos" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="usu_direccion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="usu_celular" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="usu_correo" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="usu_fecha_creacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="usu_fecha_cumple" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="usu_nick" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="usu_contraseña" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="usu_intentos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="usu_codigo_OTP" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="usu_estado" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="tusu_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="usu_fecha_ultimo_intento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="usu_foto_perfil" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="tbl_usuario_tbl_usuario_foto" Member="tbl_usuario_foto" ThisKey="usu_id" OtherKey="usu_id" Type="tbl_usuario_foto" />
      <Association Name="tbl_tipo_usuario_tbl_usuario" Member="tbl_tipo_usuario" ThisKey="tusu_id" OtherKey="tusu_id" Type="tbl_tipo_usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_usuario_foto" Member="tbl_usuario_foto">
    <Type Name="tbl_usuario_foto">
      <Column Name="ufoto_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="usu_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ufoto_datos" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ufoto_es_principal" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tbl_usuario_tbl_usuario_foto" Member="tbl_usuario" ThisKey="usu_id" OtherKey="usu_id" Type="tbl_usuario" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.desencriptacion" Method="desencriptacion" IsComposable="true">
    <Parameter Name="clave" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.encriptacion" Method="encriptacion" IsComposable="true">
    <Parameter Name="clave" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Data.Linq.Binary" />
  </Function>
  <Function Name="dbo.sp_reiniciarIntentosDiarios" Method="sp_reiniciarIntentosDiarios">
    <Return Type="System.Int32" />
  </Function>
</Database>