//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monolito4_B.Seguridad
{
    public partial class RegistroExito
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Literal litNota;
        protected global::System.Web.UI.WebControls.Image imgQr;
        protected global::System.Web.UI.WebControls.Button btnIrLogin;
    }
}
