//------------------------------------------------------------------------------
// <auto-generated />
//------------------------------------------------------------------------------

namespace Monolito4_B.Mantenimiento
{
    public partial class Desbloqueo
    {
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.GridView gvBloqueados;
    }
}
