//------------------------------------------------------------------------------
// <auto-generated />
//------------------------------------------------------------------------------

namespace Monolito4_B.Mantenimiento
{
    public partial class Inicio
    {
        protected global::System.Web.UI.WebControls.Image imgDashAvatar;
        protected global::System.Web.UI.WebControls.Label lblActivos;
        protected global::System.Web.UI.WebControls.Label lblBloq;
        protected global::System.Web.UI.WebControls.Label lblTotal;
        protected global::System.Web.UI.WebControls.Panel pnlAdminInfo;
        protected global::System.Web.UI.WebControls.Panel pnlUsuarioInfo;
        protected global::System.Web.UI.WebControls.Label lblErrorDash;
    }
}
