//------------------------------------------------------------------------------
// <auto-generated />
//------------------------------------------------------------------------------

namespace Monolito4_B.Mantenimiento
{
    public partial class Juego
    {
        protected global::System.Web.UI.WebControls.Label lblTurno;
        protected global::System.Web.UI.WebControls.Button btnC0;
        protected global::System.Web.UI.WebControls.Button btnC1;
        protected global::System.Web.UI.WebControls.Button btnC2;
        protected global::System.Web.UI.WebControls.Button btnC3;
        protected global::System.Web.UI.WebControls.Button btnC4;
        protected global::System.Web.UI.WebControls.Button btnC5;
        protected global::System.Web.UI.WebControls.Button btnC6;
        protected global::System.Web.UI.WebControls.Button btnC7;
        protected global::System.Web.UI.WebControls.Button btnC8;
        protected global::System.Web.UI.WebControls.Button btnReiniciar;
        protected global::System.Web.UI.WebControls.Panel pnlFin;
        protected global::System.Web.UI.WebControls.Literal litFin;
    }
}
