//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monolito4_B.Mantenimiento
{
    public partial class MiPerfil
    {
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.Image imgAvatar;
        protected global::System.Web.UI.WebControls.Literal litCedula;
        protected global::System.Web.UI.WebControls.Literal litTipo;
        protected global::System.Web.UI.WebControls.TextBox txtNick;
        protected global::System.Web.UI.WebControls.TextBox txtCelular;
        protected global::System.Web.UI.WebControls.TextBox txtNombres;
        protected global::System.Web.UI.WebControls.TextBox txtApellidos;
        protected global::System.Web.UI.WebControls.TextBox txtFechaNac;
        protected global::System.Web.UI.WebControls.TextBox txtCorreo;
        protected global::System.Web.UI.WebControls.TextBox txtDireccion;
        protected global::System.Web.UI.WebControls.TextBox txtPassword;
        protected global::System.Web.UI.WebControls.FileUpload fuPerfil;
        protected global::System.Web.UI.WebControls.Button btnPrevPerfil;
        protected global::System.Web.UI.WebControls.Image imgPreviewPerfil;
        protected global::System.Web.UI.WebControls.FileUpload fuGaleria;
        protected global::System.Web.UI.WebControls.Button btnValidarGaleria;
        protected global::System.Web.UI.WebControls.Panel pnlGaleria;
        protected global::System.Web.UI.WebControls.Repeater rptGaleria;
        protected global::System.Web.UI.WebControls.Button btnGuardar;
    }
}
