//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo genera el patrón estándar de ASP.NET Web Forms (master + code-behind).
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monolito4_B.Mantenimiento
{
    public partial class Principal
    {
        protected global::System.Web.UI.WebControls.ContentPlaceHolder head;
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Image imgSidebarAvatar;
        protected global::System.Web.UI.WebControls.Label lblRolBadge;
        protected global::System.Web.UI.WebControls.Label lbl_nse;
        protected global::System.Web.UI.WebControls.Panel adm;
        protected global::System.Web.UI.WebControls.Panel usu;
        protected global::System.Web.UI.WebControls.LinkButton btnCerrarSesion;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder1;
    }
}
